version: "3"

services:
  card_ui:
    build: ./CardgameUI
    ports:
      - "8080:80"

  card_backend:
    build: ./CardGameServer/CardGameServer
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
