FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY CardGameUI.csproj .
RUN dotnet restore "CardGameUI.csproj"
COPY . .
RUN dotnet build "CardGameUI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CardGameUI.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /src/bin/Release/net5.0/publish/wwwroot .
COPY /nginx/default.conf /etc/nginx/nginx.conf

EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]